[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/p/coming-soon/*"
  to = "https://leenashitposts.substack.com/p/coming-soon/:splat"
  force = true
  status= 200


[[redirects]]
  from = "/api/*"
  to = "https://leenashitposts.substack.com/api/:splat"
  force = true
  status= 200


[[redirects]]
  from = "/icons/*"
  to = "https://leenashitposts.substack.com/icons/:splat"
  force = true
  status= 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200