[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/p/coming-soon//*"
  to = "https://leenashitposts.substack.com/:splat"
  force = true
  status= 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200